# Generated by Django 2.1.5 on 2019-01-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('items', models.ManyToManyField(related_name='_shoppingcart_items_+', to='products.Product')),
            ],
        ),
    ]
