# Generated by Django 2.1.5 on 2019-01-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0002_auto_20190110_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=100)),
                ('items', models.ManyToManyField(to='products.Product')),
            ],
        ),
    ]
