# Generated by Django 2.1.5 on 2019-01-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingCart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='items',
            field=models.ManyToManyField(related_name='_shoppingcart_items_+', to='products.Product'),
        ),
    ]
